[ether]
addr = "ws://ethereum-2:8546"
name = "ether"
contract_address = "0x668a209Dc6562707469374B8235e37b8eC25db08"
key_path = "account.key"
password = "password"
min_confirm = 1
timeout_height = 10
timeout_period = 60
offchain_limit = 50
